apiVersion: apps/v1
kind:  Deployment
metadata:
  name: cm-kube-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-nginx
  template:
    metadata:
      labels:
        app: kube-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.18-alpine
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: kube-nginx-conf
          readOnly: true

        
      volumes:
      - name: kube-nginx-conf
        configMap:
          name: kube-nginx-conf
          items:
            - key: nginx.index
              path: index.html
